/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -c DBusServiceIfAdaptor -a dbusserviceifadaptor.h:dbusserviceifadaptor.cpp ./daemon/com.smack.demo.xml
 *
 * qdbusxml2cpp is Copyright (C) 2011 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef DBUSSERVICEIFADAPTOR_H_1320236241
#define DBUSSERVICEIFADAPTOR_H_1320236241

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;

/*
 * Adaptor class for interface com.smack.demo
 */
class DBusServiceIfAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "com.smack.demo")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"com.smack.demo\">\n"
"    <method name=\"setState\">\n"
"      <arg direction=\"in\" type=\"i\" name=\"state\"/>\n"
"      <arg direction=\"out\" type=\"b\"/>\n"
"    </method>\n"
"    <signal name=\"stateChanged\">\n"
"      <arg direction=\"out\" type=\"i\" name=\"state\"/>\n"
"    </signal>\n"
"  </interface>\n"
        "")
public:
    DBusServiceIfAdaptor(QObject *parent);
    virtual ~DBusServiceIfAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    bool setState(int state);
Q_SIGNALS: // SIGNALS
    void stateChanged(int state);
};

#endif
